### ISSUE TITLE
Şehirler ve karışıklık

### ISSUE THREAD

**Issue by ZgrK** [o/yurtdisinda-calismak-wiki#12]
Merhabalar,

Acaba şehirleri ülkeler altında ayırsak mı yoksa başlık altında mı ayırsak ? Çünkü bazı şehirlerde bazı durumlar farklı olabiliyor.

Mesela Bulgaristan örneğinde ulaşım, Sofia'da 1.6 leva Varna'da 1 leva çok ufak bir örnek oldu fakat bunun dışında **nereye gidilir, Etkinlikler, festivaller** gibi durumlar da çok değişiklik gösterebilir diye düşünüyorum. Tek başlık altında gidersek mesela bu gibi konular da makaleler çok uzayacak ve karmaşalar olacak gibi ön görüyorum.

Bu durum için görüşleriniz nelerdir ?

**Comment by o** [comment]
@ZgrK Ozgur merhaba abi, elimizde yeterince sehirler bazinda sayfalar oldugunda hiyerarsik olarak listeleyip ayirabiliriz. Su an icin gecici cozum olarak "Bulgaristanda toplu ulasim (genel konular), Sofya'da ulasim, Varna'da ulasim" gibi ayri ayri sayfalar olusturmakta bir sakinca gormuyorum.

**Comment by ZgrK** [comment]
@o Osman merhaba abi, tamamdır ozaman dediğin şekilde devam ediyorum ben.
