### ISSUE TITLE
Estonia

### ISSUE THREAD

**Issue by yasinaydin** [o/yurtdisinda-calismak-wiki#2]
I know it's not directly related but here's a repo I used for myself about Estonia: https://github.com/yasinaydin/estonia

Can we/where can we put it on the website?

**Comment by o** [comment]
Sure but, you meant only link to your repository? Or moving all content to this website?

For the second option, we have to organize your pages. And rather than just links, it's nice to add some sort of short information in Turkish to make pages more informational.

So, what do you prefer?

**Comment by yasinaydin** [comment]
For now we can add just the link, if we can.

For the future, if there's some demand, then I can also try writing some contnet in Turkish :)

**Comment by o** [comment]
Ok cool, could you create a pull request to add direct link to your repository from home page (Under to Netherlands section)?
