### ISSUE TITLE
Stop Abusing Me, Osman Ungur!!!! Pay BACK

### ISSUE THREAD

**Issue by clairenl** [o/yurtdisinda-calismak-wiki#20]
I feel living now is so painful cuz you abused me to Sex/blowjob/ masturbation and dumped me, unblock me 😢😭😿 fix it. Fuck!!!!!! You said, you don't like me, then why still asked me to send those nudes photos to you, huh? Unblock me and pay back. 😭😭😭😭😭 Osman Ungur!!!
![IMG_20190912_032619_243](https://user-images.githubusercontent.com/55034499/64917903-b435c600-d796-11e9-9cf2-ec5a614dc89f.jpg)

![Screenshot_20190827-112539](https://user-images.githubusercontent.com/55034499/64917899-a122f600-d796-11e9-9ead-4e3a6318a77c.jpg)

**Comment by osmanungur** [comment]
![IMG_-gwwodu](https://user-images.githubusercontent.com/55034499/64918100-f14f8780-d799-11e9-8a40-ffaed756cafb.jpg)
![IMG_r8n214](https://user-images.githubusercontent.com/55034499/64918104-ff050d00-d799-11e9-9102-22596147b82e.jpg)
![IMG_-828abu](https://user-images.githubusercontent.com/55034499/64918106-0f1cec80-d79a-11e9-965c-a2d77d98297f.jpg)
![IMG_gceou6](https://user-images.githubusercontent.com/55034499/64918115-1b08ae80-d79a-11e9-921f-cb2cc1771dae.jpg)

**Comment by osmanungur** [comment]
![IMG_-dls2hw](https://user-images.githubusercontent.com/55034499/64918128-412e4e80-d79a-11e9-89c1-f5852b55793d.jpg)
